# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/zhendong-manjaro/文档/code/AI/ai.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_about(object):
    def setupUi(self, about):
        about.setObjectName("about")
        about.resize(337, 446)
        self.label = QtWidgets.QLabel(about)
        self.label.setGeometry(QtCore.QRect(90, 20, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(about)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 51, 51))
        self.label_2.setObjectName("label_2")
        self.tabWidget = QtWidgets.QTabWidget(about)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 321, 351))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 57, 18))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(30, 80, 231, 18))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(30, 130, 231, 21))
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(30, 190, 131, 18))
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 81, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 131, 18))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(20, 90, 171, 31))
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(30, 40, 211, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(30, 100, 261, 18))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_3, "")
        self.label_12 = QtWidgets.QLabel(about)
        self.label_12.setGeometry(QtCore.QRect(90, 50, 81, 18))
        self.label_12.setObjectName("label_12")

        self.retranslateUi(about)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(about)

    def retranslateUi(self, about):
        _translate = QtCore.QCoreApplication.translate
        about.setWindowTitle(_translate("about", "关于"))
        self.label.setText(_translate("about", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">冬冬</span></p></body></html>"))
        self.label_2.setText(_translate("about", "<div style=\"border-rudius: 10px;\">\n"
"<img src=\"http://47.108.139.27:2030/side/%E5%82%AC%E9%80%9D%E5%91%98.php\">\n"
"</div>"))
        self.label_3.setText(_translate("about", "智能对话"))
        self.label_4.setText(_translate("about", "Copyright © 2022 ZhenDong"))
        self.label_5.setText(_translate("about", "<a href=\"https://www.gnu.org/licenses/gpl-3.0.en.html\">许可证：GNU通用公共许可证3.0</a>"))
        self.label_11.setText(_translate("about", "此程序不提供任何担保"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("about", "关于"))
        self.label_6.setText(_translate("about", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">QT</span></p></body></html>"))
        self.label_7.setText(_translate("about", "版本 5.15.2"))
        self.label_8.setText(_translate("about", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Wayland 窗口系统</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("about", "组件"))
        self.label_9.setText(_translate("about", "<html><head/><body><p><span style=\" font-size:14pt;\">刘振冬</span></p></body></html>"))
        self.label_10.setText(_translate("about", "电子邮箱：donggggggg121212@163.com"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("about", "开发人员"))
        self.label_12.setText(_translate("about", "版本：v1.0.0"))
